### ISSUE TITLE
Inventory tracking

### ISSUE THREAD

**Issue by SquidDev** [SquidDev/artist#3]
There are several improvements which could be made to inventory tracking:

 - [x] Track every slot in the inventory so we know where items are going to go instead of rescanning after each insert.
 - [x] Don't insert into slots which are already full. This requires knowing the max stack size of an item. I could export this into the `recipe_dump.json` file.
 - [x] Don't stack/group items with different NBT. Maybe we could try to work out if they do, and store which items do and don't.
 - [x] Periodically re-scan chests to ensure they are up to date.
 - [x] Persist inventory cache, and rescan in background instead.
